package com.player.blog.Dao;

import com.player.blog.POJO.DO.ArticleDO;
import com.player.blog.POJO.VO.ArticleVO;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface ArticleDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Sat Jun 08 20:47:46 CST 2019
     */
    int deleteByPrimaryKey(ArticleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Sat Jun 08 20:47:46 CST 2019
     */
    int insert(ArticleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Sat Jun 08 20:47:46 CST 2019
     */
    int insertSelective(ArticleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Sat Jun 08 20:47:46 CST 2019
     */
    ArticleDO selectByPrimaryKey(ArticleDO articleDO);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Sat Jun 08 20:47:46 CST 2019
     */
    int updateByPrimaryKeySelective(ArticleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Sat Jun 08 20:47:46 CST 2019
     */
    int updateByPrimaryKey(ArticleDO record);
    List<ArticleDO> getRecommend();
    List<ArticleDO> getHot();
    String getContent(Long id);
    List<ArticleDO> searchArticle(String title);
    List<ArticleDO> getArticle(String username);
    List<ArticleDO> getPublicArticle(String username);
    List<ArticleDO> getFriendArticle(List<String> friendList);
}