package com.player.blog.Dao;

import com.player.blog.POJO.DO.FriendDO;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface FriendDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend
     *
     * @mbg.generated Sat Jun 22 18:43:51 CST 2019
     */
    int deleteByPrimaryKey(String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend
     *
     * @mbg.generated Sat Jun 22 18:43:51 CST 2019
     */
    int insert(FriendDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend
     *
     * @mbg.generated Sat Jun 22 18:43:51 CST 2019
     */
    int insertSelective(FriendDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend
     *
     * @mbg.generated Sat Jun 22 18:43:51 CST 2019
     */
    FriendDO selectByPrimaryKey(String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend
     *
     * @mbg.generated Sat Jun 22 18:43:51 CST 2019
     */
    int updateByPrimaryKeySelective(FriendDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend
     *
     * @mbg.generated Sat Jun 22 18:43:51 CST 2019
     */
    int updateByPrimaryKey(FriendDO record);



    List<FriendDO>  selectByUsername(String username);
    List<String>  newFriend(String username);
    String  isFriend(@Param("username") String username,@Param("friend")String friend);
    String  isApply(@Param("username") String username,@Param("friend")String friend);

}