package com.player.blog.POJO.VO;

import java.util.Date;

public class ArticleVO {
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.username
     *
     * @mbg.generated Sat Jun 08 20:47:46 CST 2019
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.time
     *
     * @mbg.generated Sat Jun 08 20:47:46 CST 2019
     */
    private String time;
    private String content;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.title
     *
     * @mbg.generated Sat Jun 08 20:47:46 CST 2019
     */
    private String title;
    private String first;
    private Long like;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.content
     *
     * @mbg.generated Sat Jun 08 20:47:46 CST 2019
     */

    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.id
     *
     * @param id the value for article.id
     *
     * @mbg.generated Sat Jun 08 20:47:46 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.username
     *
     * @return the value of article.username
     *
     * @mbg.generated Sat Jun 08 20:47:46 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.username
     *
     * @param username the value for article.username
     *
     * @mbg.generated Sat Jun 08 20:47:46 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.time
     *
     * @return the value of article.time
     *
     * @mbg.generated Sat Jun 08 20:47:46 CST 2019
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.title
     *
     * @return the value of article.title
     *
     * @mbg.generated Sat Jun 08 20:47:46 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.title
     *
     * @param title the value for article.title
     *
     * @mbg.generated Sat Jun 08 20:47:46 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }


    public String getFirst() {
        return first;
    }

    public void setFirst(String first) {
        this.first = first;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public Long getLike() {
        return like;
    }

    public void setLike(Long like) {
        this.like = like;
    }
}
