package com.player.blog.POJO.VO;

public class InformationVO {
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column information.nickname
     *
     * @mbg.generated Sat Jun 08 20:22:58 CST 2019
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column information.avatar
     *
     * @mbg.generated Sat Jun 08 20:22:58 CST 2019
     */
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column information.gender
     *
     * @mbg.generated Sat Jun 08 20:22:58 CST 2019
     */
    private Byte gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column information.slogan
     *
     * @mbg.generated Sat Jun 08 20:22:58 CST 2019
     */
    private String slogan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column information.birthday
     *
     * @mbg.generated Sat Jun 08 20:22:58 CST 2019
     */
    private String  birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column information.essay
     *
     * @mbg.generated Sat Jun 08 20:22:58 CST 2019
     */
    private Integer essay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column information.friend
     *
     * @mbg.generated Sat Jun 08 20:22:58 CST 2019
     */
    private Integer friend;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column information.blogname
     *
     * @mbg.generated Sat Jun 08 20:22:58 CST 2019
     */
    private String blogname;

    public String getBlogname() {
        return blogname;
    }

    public void setBlogname(String blogname) {
        this.blogname = blogname;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getNickname() {
        return nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public String getAvatar() {
        return avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    public Byte getGender() {
        return gender;
    }

    public void setGender(Byte gender) {
        this.gender = gender;
    }

    public String getSlogan() {
        return slogan;
    }

    public void setSlogan(String slogan) {
        this.slogan = slogan;
    }

    public String getBirthday() {
        return birthday;
    }

    public void setBirthday(String birthday) {
        this.birthday = birthday;
    }

    public Integer getEssay() {
        return essay;
    }

    public void setEssay(Integer essay) {
        this.essay = essay;
    }

    public Integer getFriend() {
        return friend;
    }

    public void setFriend(Integer friend) {
        this.friend = friend;
    }
}
