package com.player.blog.POJO.DO;

public class FriendDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend.username
     *
     * @mbg.generated Sat Jun 22 18:43:51 CST 2019
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend.friend
     *
     * @mbg.generated Sat Jun 22 18:43:51 CST 2019
     */
    private String friend;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend.apply
     *
     * @mbg.generated Sat Jun 22 18:43:51 CST 2019
     */
    private Byte apply;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend.username
     *
     * @return the value of friend.username
     *
     * @mbg.generated Sat Jun 22 18:43:51 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend.username
     *
     * @param username the value for friend.username
     *
     * @mbg.generated Sat Jun 22 18:43:51 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend.friend
     *
     * @return the value of friend.friend
     *
     * @mbg.generated Sat Jun 22 18:43:51 CST 2019
     */
    public String getFriend() {
        return friend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend.friend
     *
     * @param friend the value for friend.friend
     *
     * @mbg.generated Sat Jun 22 18:43:51 CST 2019
     */
    public void setFriend(String friend) {
        this.friend = friend == null ? null : friend.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend.apply
     *
     * @return the value of friend.apply
     *
     * @mbg.generated Sat Jun 22 18:43:51 CST 2019
     */
    public Byte getApply() {
        return apply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend.apply
     *
     * @param apply the value for friend.apply
     *
     * @mbg.generated Sat Jun 22 18:43:51 CST 2019
     */
    public void setApply(Byte apply) {
        this.apply = apply;
    }
}