package com.player.blog.POJO.DO;

import java.util.Date;

public class InformationDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column information.username
     *
     * @mbg.generated Sat Jun 08 20:22:58 CST 2019
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column information.nickname
     *
     * @mbg.generated Sat Jun 08 20:22:58 CST 2019
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column information.avatar
     *
     * @mbg.generated Sat Jun 08 20:22:58 CST 2019
     */
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column information.gender
     *
     * @mbg.generated Sat Jun 08 20:22:58 CST 2019
     */
    private Byte gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column information.slogan
     *
     * @mbg.generated Sat Jun 08 20:22:58 CST 2019
     */
    private String slogan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column information.birthday
     *
     * @mbg.generated Sat Jun 08 20:22:58 CST 2019
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column information.essay
     *
     * @mbg.generated Sat Jun 08 20:22:58 CST 2019
     */
    private Integer essay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column information.friend
     *
     * @mbg.generated Sat Jun 08 20:22:58 CST 2019
     */
    private Integer friend;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column information.blogname
     *
     * @mbg.generated Sat Jun 08 20:22:58 CST 2019
     */
    private String blogname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column information.username
     *
     * @return the value of information.username
     *
     * @mbg.generated Sat Jun 08 20:22:58 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column information.username
     *
     * @param username the value for information.username
     *
     * @mbg.generated Sat Jun 08 20:22:58 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column information.nickname
     *
     * @return the value of information.nickname
     *
     * @mbg.generated Sat Jun 08 20:22:58 CST 2019
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column information.nickname
     *
     * @param nickname the value for information.nickname
     *
     * @mbg.generated Sat Jun 08 20:22:58 CST 2019
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column information.avatar
     *
     * @return the value of information.avatar
     *
     * @mbg.generated Sat Jun 08 20:22:58 CST 2019
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column information.avatar
     *
     * @param avatar the value for information.avatar
     *
     * @mbg.generated Sat Jun 08 20:22:58 CST 2019
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column information.gender
     *
     * @return the value of information.gender
     *
     * @mbg.generated Sat Jun 08 20:22:58 CST 2019
     */
    public Byte getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column information.gender
     *
     * @param gender the value for information.gender
     *
     * @mbg.generated Sat Jun 08 20:22:58 CST 2019
     */
    public void setGender(Byte gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column information.slogan
     *
     * @return the value of information.slogan
     *
     * @mbg.generated Sat Jun 08 20:22:58 CST 2019
     */
    public String getSlogan() {
        return slogan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column information.slogan
     *
     * @param slogan the value for information.slogan
     *
     * @mbg.generated Sat Jun 08 20:22:58 CST 2019
     */
    public void setSlogan(String slogan) {
        this.slogan = slogan == null ? null : slogan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column information.birthday
     *
     * @return the value of information.birthday
     *
     * @mbg.generated Sat Jun 08 20:22:58 CST 2019
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column information.birthday
     *
     * @param birthday the value for information.birthday
     *
     * @mbg.generated Sat Jun 08 20:22:58 CST 2019
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column information.essay
     *
     * @return the value of information.essay
     *
     * @mbg.generated Sat Jun 08 20:22:58 CST 2019
     */
    public Integer getEssay() {
        return essay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column information.essay
     *
     * @param essay the value for information.essay
     *
     * @mbg.generated Sat Jun 08 20:22:58 CST 2019
     */
    public void setEssay(Integer essay) {
        this.essay = essay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column information.friend
     *
     * @return the value of information.friend
     *
     * @mbg.generated Sat Jun 08 20:22:58 CST 2019
     */
    public Integer getFriend() {
        return friend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column information.friend
     *
     * @param friend the value for information.friend
     *
     * @mbg.generated Sat Jun 08 20:22:58 CST 2019
     */
    public void setFriend(Integer friend) {
        this.friend = friend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column information.blogname
     *
     * @return the value of information.blogname
     *
     * @mbg.generated Sat Jun 08 20:22:58 CST 2019
     */
    public String getBlogname() {
        return blogname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column information.blogname
     *
     * @param blogname the value for information.blogname
     *
     * @mbg.generated Sat Jun 08 20:22:58 CST 2019
     */
    public void setBlogname(String blogname) {
        this.blogname = blogname == null ? null : blogname.trim();
    }
}