package com.player.blog.POJO.DO;

public class LikeDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column like.articleId
     *
     * @mbg.generated Wed Jun 26 16:05:50 CST 2019
     */
    private Long articleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column like.username
     *
     * @mbg.generated Wed Jun 26 16:05:50 CST 2019
     */
    private String username;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column like.articleId
     *
     * @return the value of like.articleId
     *
     * @mbg.generated Wed Jun 26 16:05:50 CST 2019
     */
    public Long getArticleid() {
        return articleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column like.articleId
     *
     * @param articleid the value for like.articleId
     *
     * @mbg.generated Wed Jun 26 16:05:50 CST 2019
     */
    public void setArticleid(Long articleid) {
        this.articleid = articleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column like.username
     *
     * @return the value of like.username
     *
     * @mbg.generated Wed Jun 26 16:05:50 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column like.username
     *
     * @param username the value for like.username
     *
     * @mbg.generated Wed Jun 26 16:05:50 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }
}